# Generated by Django 5.1.2 on 2024-10-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_answer_answer_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
