# Generated by Django 5.1.2 on 2024-10-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_article_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
    ]
