# Generated by Django 5.1.2 on 2024-10-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_remove_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail_file',
            field=models.ImageField(blank=True, null=True, upload_to='article_thumbnails/'),
        ),
    ]
