# Generated by Django 5.1.2 on 2024-10-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_article_thumbnail_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumbnail_url',
        ),
    ]
