# Generated by Django 5.1.2 on 2024-10-22 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('categories', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('resto_name', models.CharField(max_length=250)),
                ('kecamatan', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makanan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
