# Generated by Django 5.1.2 on 2024-10-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='categories',
            field=models.CharField(choices=[('Makanan Laut', 'Makanan Laut'), ('Makanan Tradisional', 'Makanan Tradisional'), ('Makanan Sehat', 'Makanan Sehat'), ('Makanan Cepat Saji', 'Makanan Cepat Saji'), ('Makanan Penutup', 'Makanan Penutup')], max_length=100),
        ),
    ]
