# Generated by Django 5.1.2 on 2024-10-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_makanan_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Makanan',
        ),
    ]
