# Generated by Django 5.1.1 on 2024-12-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewentry',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
