# Generated by Django 5.1.2 on 2024-10-23 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_reviewentry_delete_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewentry',
            old_name='product',
            new_name='menu_item',
        ),
    ]
