# Generated by Django 5.1.1 on 2024-12-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_reviewentry_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewentry',
            name='image_url',
        ),
    ]
