# Generated by Django 5.1.2 on 2024-10-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='kecamatan',
            field=models.CharField(choices=[('Kebayoran Lama', 'Kebayoran Lama'), ('Kebayoran Baru', 'Kebayoran Baru'), ('Cilandak', 'Cilandak'), ('Mampang Prapatan', 'Mampang Prapatan'), ('Jagakarsa', 'Jagakarsa'), ('Pancoran', 'Pancoran'), ('Pasar Minggu', 'Pasar Minggu'), ('Pesanggrahan', 'Pesanggrahan'), ('Setiabudi', 'Setiabudi'), ('Tebet', 'Tebet')], max_length=100),
        ),
    ]
