# Generated by Django 5.1.2 on 2024-12-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(null=True),
        ),
    ]
